# Generated by nixos-generate-config on box. Keep hardware changes separate.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot = {
    initrd.availableKernelModules = [
      "nvme"
      "xhci_pci"
      "ahci"
      "usbhid"
      "usb_storage"
      "sd_mod"
    ];
    kernelModules = [ "kvm-amd" ];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/2ebffb1f-8519-4099-bf5c-574bcbbfa53f";
      fsType = "btrfs";
    };

    "/home" = {
      device = "/dev/disk/by-uuid/2ebffb1f-8519-4099-bf5c-574bcbbfa53f";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

    "/nix" = {
      device = "/dev/disk/by-uuid/2ebffb1f-8519-4099-bf5c-574bcbbfa53f";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/BEA1-EE63";
      fsType = "vfat";
      options = [
        "fmask=0077"
        "dmask=0077"
      ];
    };

    "/srv/photos" = {
      device = "/dev/disk/by-label/photos";
      fsType = "ext4";
      options = [ "noatime" ];
    };

    "/srv/data" = {
      device = "/dev/disk/by-label/data";
      fsType = "ext4";
      options = [ "noatime" ];
    };
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
